name: OpenCart Test Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on PRs to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI Tests (Selenium)
        run: pytest tests/ui_tests/

      - name: Run API Tests (Requests)
        run: pytest tests/api_tests/

      - name: Run Performance Tests (Locust)
        run: locust -f tests/performance_tests/load_test_locust.py --host=https://the-internet.herokuapp.com
