name: OpenCart Test Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run UI Tests (Selenium with pytest)
    - name: Run UI Tests
      run: |
        pytest tests/ui_tests/test_ui.py  # Running UI tests from this file

    # Run API Tests (requests with pytest)
    - name: Run API Tests
      run: |
        pytest tests/api_tests/test_api.py  # Running API tests from this file

    # Run Performance Tests (Locust)
    - name: Run Performance Tests (Locust)
      run: |
        locust -f tests/performance_tests/load_test_locust.py --headless --users 10 --spawn-rate 1 --host=https://the-internet.herokuapp.com/  # Running Locust performance tests
