name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the OS where the job will run

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # This checks out the code from your GitHub repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set the Python version you are using

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run UI Tests
        run: |
          pytest tests/ui_tests/test_ui.py  # Run UI tests using pytest

      - name: Run API Tests
        run: |
          pytest tests/api_tests/test_products.py  # Run API tests using pytest
