name: Run Tests

on:
  push:
    branches:
      - main  # Trigger the workflow for pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the OS where the job will run

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # This checks out the code from your GitHub repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set the Python version you are using

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run UI Tests
        run: |
          echo "Running UI tests..."
          pytest tests/ui_tests/test_ui.py  # Run UI tests using pytest (adjust path if necessary)

      - name: Run API Tests
        run: |
          echo "Running API tests..."
          pytest tests/api_tests/test_products.py  # Run API tests using pytest (adjust path if necessary)

      - name: Run Load Tests (Locust)
        run: |
          echo "Running Load tests..."
          locust -f tests/performance_tests/load_test_locust.py --host=https://the-internet.herokuapp.com  # Run Locust load tests (adjust path if necessary)

      - name: Upload Test Results
        if: always()  # Always upload test results, even if some tests fail
        uses: actions/upload-artifact@v2  # Update to v2 to avoid deprecation
        with:
          name: test-results
          path: ./test_results/  # Adjust path if necessary to save test results as artifacts
