name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers (if using Playwright)
        run: playwright install
        continue-on-error: true  # Skip errors if Playwright is not used

      - name: Verify Installed Packages
        run: pip list

      - name: Run UI Tests
        run: pytest tests/ui_tests/ --maxfail=5 --disable-warnings

      - name: Run API Tests
        run: pytest tests/api_tests/ --maxfail=5 --disable-warnings

      - name: Run Load Tests (Locust)
        run: locust -f tests/performance_tests/load_test_locust.py --host=https://the-internet.herokuapp.com --headless -u 10 -r 2 --run-time 1m
        continue-on-error: true

      - name: Save Test Results
        run: mkdir -p test_results && pytest --junitxml=test_results/results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results/
